# Generated by Django 6.0.1 on 2026-01-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NatureReserve",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_data", models.JSONField()),
                ("tags", models.JSONField(default=dict)),
                ("area_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nature_reserves",
                "indexes": [
                    models.Index(
                        fields=["area_type"], name="nature_rese_area_ty_096c9f_idx"
                    ),
                    models.Index(fields=["name"], name="nature_rese_name_2f420d_idx"),
                ],
            },
        ),
    ]
