# Generated by Django 6.0.2 on 2026-02-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportGrid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grid_number",
                    models.PositiveIntegerField(
                        help_text="1-based index of this tile in the bbox when last processed"
                    ),
                ),
                ("min_lon", models.FloatField()),
                ("min_lat", models.FloatField()),
                ("max_lon", models.FloatField()),
                ("max_lat", models.FloatField()),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("reserves_created_count", models.PositiveIntegerField(default=0)),
                ("reserves_updated_count", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "import_grids",
                "ordering": ["grid_number"],
                "indexes": [
                    models.Index(
                        fields=["success"], name="import_grid_success_5c9fa0_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="import_grid_last_up_50dd18_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("min_lon", "min_lat", "max_lon", "max_lat"),
                        name="import_grid_bbox_unique",
                    )
                ],
            },
        ),
    ]
