# Generated by Django 6.0.2 on 2026-02-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_import_grid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "operators",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="importgrid",
            name="grid_number",
            field=models.PositiveIntegerField(
                help_text="1-based tile index from the run that last processed this grid. Depends on the bbox used in that run; resume uses bbox coordinates only."
            ),
        ),
        migrations.AddField(
            model_name="naturereserve",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nature_reserves",
                to="api.operator",
            ),
        ),
    ]
