# Generated by Django 6.0.2 on 2026-02-13 20:28

from django.db import migrations, models


def copy_operator_to_operators(apps, schema_editor):
    NatureReserve = apps.get_model("api", "NatureReserve")
    for reserve in NatureReserve.objects.filter(operator_id__isnull=False):
        reserve.operators.add(reserve.operator_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_operator_model_and_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturereserve",
            name="operators",
            field=models.ManyToManyField(
                blank=True, related_name="nature_reserves", to="api.operator"
            ),
        ),
        migrations.RunPython(copy_operator_to_operators, noop),
        migrations.RemoveField(
            model_name="naturereserve",
            name="operator",
        ),
    ]
