# Generated by Django 6.0.2 on 2026-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_nature_reserve_operators_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturereserve",
            name="max_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naturereserve",
            name="max_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naturereserve",
            name="min_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naturereserve",
            name="min_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="naturereserve",
            index=models.Index(
                fields=["min_lat", "max_lat", "min_lon", "max_lon"],
                name="nature_rese_min_lat_f479ba_idx",
            ),
        ),
    ]
