# Generated by Django 6.0.2 on 2026-02-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_add_nature_reserve_bbox"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="naturereserve",
            name="nature_rese_min_lat_f479ba_idx",
        ),
        migrations.AddIndex(
            model_name="naturereserve",
            index=models.Index(
                condition=models.Q(
                    ("max_lat__isnull", False),
                    ("max_lon__isnull", False),
                    ("min_lat__isnull", False),
                    ("min_lon__isnull", False),
                ),
                fields=["min_lat", "min_lon", "max_lat", "max_lon"],
                name="nature_rese_bbox_at_point_idx",
            ),
        ),
    ]
