# Generated by Django 6.0.2 on 2026-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_bbox_index_at_point"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="naturereserve",
            index=models.Index(
                condition=models.Q(
                    ("max_lat__isnull", False),
                    ("max_lon__isnull", False),
                    ("min_lat__isnull", False),
                    ("min_lon__isnull", False),
                ),
                fields=["min_lat"],
                name="nature_rese_min_lat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="naturereserve",
            index=models.Index(
                condition=models.Q(
                    ("max_lat__isnull", False),
                    ("max_lon__isnull", False),
                    ("min_lat__isnull", False),
                    ("min_lon__isnull", False),
                ),
                fields=["max_lat"],
                name="nature_rese_max_lat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="naturereserve",
            index=models.Index(
                condition=models.Q(
                    ("max_lat__isnull", False),
                    ("max_lon__isnull", False),
                    ("min_lat__isnull", False),
                    ("min_lon__isnull", False),
                ),
                fields=["min_lon"],
                name="nature_rese_min_lon_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="naturereserve",
            index=models.Index(
                condition=models.Q(
                    ("max_lat__isnull", False),
                    ("max_lon__isnull", False),
                    ("min_lat__isnull", False),
                    ("min_lon__isnull", False),
                ),
                fields=["max_lon"],
                name="nature_rese_max_lon_idx",
            ),
        ),
    ]
