# Generated by Django 6.0.2 on 2026-02-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_bbox_individual_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="naturereserve",
            name="nature_rese_bbox_at_point_idx",
        ),
        migrations.RemoveIndex(
            model_name="naturereserve",
            name="nature_rese_min_lat_idx",
        ),
        migrations.RemoveIndex(
            model_name="naturereserve",
            name="nature_rese_max_lat_idx",
        ),
        migrations.RemoveIndex(
            model_name="naturereserve",
            name="nature_rese_min_lon_idx",
        ),
        migrations.RemoveIndex(
            model_name="naturereserve",
            name="nature_rese_max_lon_idx",
        ),
        migrations.AlterField(
            model_name="naturereserve",
            name="max_lat",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturereserve",
            name="max_lon",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturereserve",
            name="min_lat",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturereserve",
            name="min_lon",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
