# Generated by Django 6.0.2 on 2026-02-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_nature_reserve_protect_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturereserve",
            name="geojson",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
