# Generated by Django 6.0.2 on 2026-02-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_nature_reserve_source_osm_data_nullable"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="naturereserve",
            name="nature_rese_area_ty_096c9f_idx",
        ),
        migrations.RemoveIndex(
            model_name="naturereserve",
            name="nature_rese_name_2f420d_idx",
        ),
        migrations.AlterField(
            model_name="naturereserve",
            name="area_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="naturereserve",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="naturereserve",
            name="protect_class",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
